---
title: "Effect modification monsoon season"
author: "Pearl Ante-Testard"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: default
    highlight: default
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
knit: (function(inputFile, encoding) {
        rmarkdown::render(inputFile, 
                          encoding   = encoding, 
                          output_dir = here::here("2-initial-analysis/output")
                          )})
---

```{r setup, include=FALSE}

library(geepack)
library(lmtest)
library(sandwich)
library(cowplot)
library(gridExtra)

```

```{r clean environment, echo=FALSE}

rm(list=ls(all=TRUE))
```

```{r configuration, message=FALSE}

library(here)
source(here::here("2-initial-analysis/R", "0-config.R"))
```

```{r read formatted data, message=FALSE}

#df_analysis <- readRDS(file = here::here("1-data", "2-final",
                      #"enrol_diar_tr_wealth_indiv_svy012.rds"))

# Surveys 1 and 2 (8440 children)
df_analysis_svy12 <- readRDS(file = here::here("1-data", "2-final",
                      "enrol_diar_tr_wealth_indiv_svy012.rds")) %>%
                       filter(svy!=0)
```

```{r data, message=FALSE}

# rainy dates are based on the findings of Nguyen et al.
# rainy seasons (elevated precipitation): May 27 – September 27 in 2014 and April 1 – September 26 in 2015

df_analysis_svy12 <- df_analysis_svy12 %>%
  mutate(block=factor(block),
  diar7df=factor(diar7d),
  Arms=factor(tr_comb, levels = c(0,1), labels = c("Control","Intervention")),
  )

table(df_analysis_svy12$svyyear, df_analysis_svy12$svyweek)
table(df_analysis_svy12$svy, df_analysis_svy12$svyweek)
table(df_analysis_svy12$monsoon)
```

## Estimating diarrhea prevalence per monsoon season in the 2 arms

```{r diarrhea prevalence by arm and monsoon season}

df_analysis_svy12 <- df_analysis_svy12 %>%
  mutate(diar7d = case_when(
    diar7df == "0" ~ 0,
    diar7df == "1" ~ 1,
    TRUE ~ as.numeric(NA)
  ),
    monsoon_n = case_when(
      monsoon == 0 ~ 0,
      monsoon == 1 ~ 1,
      TRUE ~ as.numeric(NA)
    ))

#str(df_analysis_svy12$diar7d)
#str(df_analysis_svy12$monsoon_n)

prev_diar <- df_analysis_svy12 %>%                         
  group_by(Arms, monsoon_n) %>%         
  summarise_at(vars(diar7d),                  
               list(length = length, sum = sum, mean = mean, sd = sd)) 

print(prev_diar)
```

## Estimating PRs (Control/Intervention) and 95% CIs using log binomial


```{r geeglm}

# releving the variable Arms with the intervention arm as reference
# rationale: there were more diarrhea prevalence in the control arm
df_analysis_svy12$Arms <- relevel(df_analysis_svy12$Arms, ref = "Intervention")

# modeling a log binomial fit with interaction
glm_int_log <- glm(diar7df ~ monsoon + Arms + monsoon*Arms,
            family = binomial(link="log"),
            data = df_analysis_svy12)
summary(glm_int_log)

# get the var-cov matrix
glmfitlog_robust_vcov <- vcov(glm_int_log, cluster=df_analysis_svy12$block)

# update regression fit
glmfitlog_lin_robustse <- coeftest(glm_int_log, vcov. =  glmfitlog_robust_vcov)
print(glmfitlog_lin_robustse)

# modeling a log binomial fit with interaction
glm_noint_log <- glm(diar7df ~ monsoon + Arms,
            family = binomial(link="log"),
            data = df_analysis_svy12)
summary(glm_noint_log)
print(coeftest(glm_noint_log, vcov. =  glmfitlog_robust_vcov))

# wald test to compare the models with and without interaction
wald_pr <- waldtest(glm_int_log, glm_noint_log, vcov = glmfitlog_robust_vcov) 
print(wald_pr)

```

```{r PR estimation using log binomial}

# get PR from geemod_int

# method 1: manual
PR_dry <- exp(glm_int_log$coefficients[3])
PR_wet <- exp((glm_int_log$coefficients[1] + glm_int_log$coefficients[2] + glm_int_log$coefficients[3] + 
  glm_int_log$coefficients[4]) - (glm_int_log$coefficients[1] + glm_int_log$coefficients[2]))

# method 2
# dry
logPD_dry = glmfitlog_lin_robustse[3,1]
PR_dry <- exp(logPD_dry)
logPD_dry_se = glmfitlog_lin_robustse[3,2]
PR_dry_lower <- exp(logPD_dry-1.96*logPD_dry_se)
PR_dry_upper <- exp(logPD_dry+1.96*logPD_dry_se)
#PD_dry; PD_dry_lower; PD_dry_upper
dat_dry <- data.frame(PR_dry, PR_dry_lower, PR_dry_upper)
dat_dry$monsoonf <- "dry"
colnames(dat_dry) <- c("PR", "lower", "upper", "season")

# monsoon
lincom <- c(0,0,1,1)
logPR_wet <- t(lincom) %*% glmfitlog_lin_robustse[,1]
logPR_se_wet = sqrt( t(lincom) %*% glmfitlog_robust_vcov %*% lincom)
PR_wet <- exp(logPR_wet)
PR_wet_lower <- exp(logPR_wet-1.96*logPR_se_wet)
PR_wet_upper <- exp(logPR_wet+1.96*logPR_se_wet)
#PR_wet; PR_wet_lower; PR_wet_upper
dat_wet <- data.frame(PR_wet, PR_wet_lower, PR_wet_upper)
dat_wet$monsoonf <- "monsoon"
colnames(dat_wet) <- c("PR", "lower", "upper", "season")

# merging dataframes
dat <- rbind(dat_dry, dat_wet)

print(dat)
```

## Estimating PDs (Control - Intervention) and 95% CIs using linear-binomial

```{r glm}

# modeling a glm fit with interaction
# using the factor diar7df for glm
glm_int_iden <- glm(diar7df ~ monsoon + Arms + monsoon*Arms,
            family = binomial(link="identity"),
            data = df_analysis_svy12
            )
#summary(glm_int_iden)

# get robust var-covar matrix, allowing for block-level clustering 
glmfit_robust_iden_vcov <- vcovCL(glm_int_iden,cluster=df_analysis_svy12$block)

# update regression fit
glmfit_lin_robustse <- coeftest(glm_int_iden,vcov. =  glmfit_robust_iden_vcov)
print(glmfit_lin_robustse)

# modeling a glm fit without an interaction
glm_noint_iden <- glm(diar7df ~ monsoon + Arms,
            family = binomial(link="identity"),
            data = df_analysis_svy12
            )
#summary(glm_noint_iden)
print(coeftest(glm_noint_iden, vcov. =  glmfit_robust_iden_vcov))

# wald test to compare the models with and without interaction
wald_pd <- waldtest(glm_int_iden, glm_noint_iden, vcov = glmfit_robust_iden_vcov) 
print(wald_pd)
```


```{r PD estimation using linear-binomial}

# get PR from geemod_int

# method 1: manual
PD_dry <- glm_int_iden$coefficients[3]
PD_rainy <- (glm_int_iden$coefficients[1] + glm_int_iden$coefficients[2] + glm_int_iden$coefficients[3] + 
  glm_int_iden$coefficients[4]) - (glm_int_iden$coefficients[1] + glm_int_iden$coefficients[2])


# method 2
logPD_dry = glmfit_lin_robustse[3,1]
logPD_dry_se = glmfit_lin_robustse[3,2]
PD_dry_lower <- logPD_dry-1.96*logPD_dry_se
PD_1_upper <- logPD_dry+1.96*logPD_dry_se
#PD_dry; PD_dry_lower; PD_dry_upper
dat_pd_dry <- data.frame(logPD_dry, PD_dry_lower, PD_1_upper)
dat_pd_dry$monsoon <- "dry"
colnames(dat_pd_dry) <- c("PD", "lower", "upper", "season")

lincom_pd <- c(0,0,1,1)
logPD_wet = t(lincom_pd) %*% glmfit_lin_robustse[,1]
logPD_wet_se = sqrt( t(lincom_pd) %*% glmfit_robust_iden_vcov %*% lincom_pd)
PD_wet_lower <- logPD_wet-1.96*logPD_wet_se
PD_wet_upper <- logPD_wet+1.96*logPD_wet_se
#PR_wet; PR_wet_lower; PR_wet_upper
dat_pd_wet <- data.frame(logPD_wet, PD_wet_lower, PD_wet_upper)
dat_pd_wet$monsoon <- "monsoon"
colnames(dat_pd_wet) <- c("PD", "lower", "upper", "season")

# merging dataframes
dat_pd <- rbind(dat_pd_dry, dat_pd_wet)

print(dat_pd)
```


```{r}

####################################
##### Prevalence in dry season #####
####################################

# control
#prev_dry_control <- (glm_int_iden$coefficients[1] + glm_int_iden$coefficients[3])
lincom_prev_dry_control <- c(1,0,1,0)
log_prev_dry_control = t(lincom_prev_dry_control) %*% glmfit_lin_robustse[,1]
logprev_dry_control_se = sqrt( t(lincom_prev_dry_control) %*% glmfit_robust_iden_vcov %*% lincom_prev_dry_control)
prev_dry_control_lower <- log_prev_dry_control-1.96*logprev_dry_control_se
prev_dry_control_upper <- log_prev_dry_control+1.96*logprev_dry_control_se
prev_dry_control <- data.frame(log_prev_dry_control, prev_dry_control_lower, prev_dry_control_upper)
prev_dry_control$monsoon <- "dry"
prev_dry_control$Arms <- "control"
colnames(prev_dry_control) <- c("prevalence", "lower", "upper", "season", "Arms")
# intervention
#prev_dry_interv <- glm_int_iden$coefficients[1]
lincom_prev_dry_interv <- c(1,0,0,0)
log_prev_dry_interv = t(lincom_prev_dry_interv) %*% glmfit_lin_robustse[,1]
logprev_dry_interv_se = sqrt( t(lincom_prev_dry_interv) %*% glmfit_robust_iden_vcov %*% lincom_prev_dry_interv)
prev_dry_interv_lower <- log_prev_dry_interv-1.96*logprev_dry_interv_se
prev_dry_interv_upper <- log_prev_dry_interv+1.96*logprev_dry_interv_se
prev_dry_interv <- data.frame(log_prev_dry_interv, prev_dry_interv_lower, prev_dry_interv_upper)
prev_dry_interv$monsoon <- "dry"
prev_dry_interv$Arms <- "intervention"
colnames(prev_dry_interv) <- c("prevalence", "lower", "upper", "season", "Arms")

####################################
#### Prevalence in rainy season ####
####################################

# control
#prev_rainy_control <- (glm_int_iden$coefficients[1] + glm_int_iden$coefficients[2] + glm_int_iden$coefficients[3] + 
  #glm_int_iden$coefficients[4])
lincom_prev_rainy_control <- c(1,1,1,1)
log_prev_rainy_control = t(lincom_prev_rainy_control) %*% glmfit_lin_robustse[,1]
logprev_rainy_control_se = sqrt( t(lincom_prev_rainy_control) %*% glmfit_robust_iden_vcov %*% lincom_prev_rainy_control)
prev_rainy_control_lower <- log_prev_rainy_control-1.96*logprev_rainy_control_se
prev_rainy_control_upper <- log_prev_rainy_control+1.96*logprev_rainy_control_se
prev_rainy_control <- data.frame(log_prev_rainy_control, prev_rainy_control_lower, prev_rainy_control_upper)
prev_rainy_control$monsoon <- "monsoon"
prev_rainy_control$Arms <- "control"
colnames(prev_rainy_control) <- c("prevalence", "lower", "upper", "season", "Arms")

# intervention
#prev_rainy_interv <- (glm_int_iden$coefficients[1] + glm_int_iden$coefficients[2])
lincom_prev_rainy_interv <- c(1,1,0,0)
log_prev_rainy_interv = t(lincom_prev_rainy_interv) %*% glmfit_lin_robustse[,1]
logprev_rainy_interv_se = sqrt( t(lincom_prev_rainy_interv) %*% glmfit_robust_iden_vcov %*% lincom_prev_rainy_interv)
prev_rainy_interv_lower <- log_prev_rainy_interv-1.96*logprev_rainy_interv_se
prev_rainy_interv_upper <- log_prev_rainy_interv+1.96*logprev_rainy_interv_se
prev_rainy_interv <- data.frame(log_prev_rainy_interv, prev_rainy_interv_lower, prev_rainy_interv_upper)
prev_rainy_interv$monsoon <- "monsoon"
prev_rainy_interv$Arms <- "intervention"
colnames(prev_rainy_interv) <- c("prevalence", "lower", "upper", "season", "Arms")

# merging dataframes
dat_prev <- rbind(prev_dry_control, prev_dry_interv, prev_rainy_control, prev_rainy_interv)

print(dat_prev)

```



## Plotting Prevalence Ratio (control/intervention) and Prevalence Difference (control-intervention)

```{r plots}
# plotting diarrhea prevalence by arm and per monsoon season

plot_prev <- ggplot(data = dat_prev, 
                    aes(x = season, y = prevalence, color = Arms
                                 )) + 
             geom_errorbar(aes(ymin=lower, ymax=upper), 
                    width = 0.1, linewidth = 0.6, position = position_dodge(width = 0.4)) +
             geom_point(size = 1.5, position = position_dodge(width = 0.4)) +
             scale_color_manual(values = c('#E69F00', 'turquoise')) + 
               #theme(legend.position = "top") +
             scale_y_continuous(breaks=seq(0,0.12,by=0.02), limits=c(0,0.12),
                      labels =   sprintf("%1.0f",seq(0,0.12,by=0.02)*100)) +
             labs(x = "Season", y = "Diarrhea Prevalence (%)", tag = "A \n") + 
             theme_minimal() +
             theme(legend.position = c(0.2,0.8),
                   legend.title = element_blank(),
                   legend.key.size = unit(0.05, 'cm'),
                   text = element_text(size=7.5),
                   plot.tag = element_text(face = "bold")) 

# plotting PR control/intervention
glm_plot_pr <- ggplot(dat, aes(season, PR)) + 
               geom_errorbar(aes(ymin=lower, ymax=upper#, color = monsoon
                                 ), 
                       width = 0.06, linewidth = 0.6, position = position_dodge(width = 0.4)) +
               geom_hline(yintercept = 1, linetype="dotted") +
               geom_point(size = 1.5, position = position_dodge(width = 0.4)) +
               scale_y_continuous(breaks=c(0.5,1,1.5,2,2.5,3), trans = "log") +
               labs(x = "Season", y = "Prevalence Ratio (PR)", tag = "B \n") +
               theme_minimal() +
               theme(legend.position = "none",
                     text = element_text(size=7.5),
                     plot.tag = element_text(face = "bold")) 

# plotting PD control-intervention
glm_plot_pd <- ggplot(dat_pd, aes(season, PD)) +
               geom_errorbar(aes(ymin=lower, ymax=upper#, color = monsoon
                                 ), 
                      width = 0.06, linewidth = 0.6, position = position_dodge(width = 0.4)) +
               geom_hline(yintercept = 0, linetype="dotted") +
               geom_point(size = 1.5, position = position_dodge(width = 0.4)) +
               scale_y_continuous(breaks=seq(-0.02,0.06,by=0.02), limits=c(-0.02,0.06),
                      labels =   sprintf("%1.0f",seq(-0.02,0.06,by=0.02)*100)) +
               labs(x = "Season", y = "Prevalence Difference (PD,%)", tag = "C \n") +
               theme_minimal() +
               theme(legend.position = "none",
                     text = element_text(size=7.5),
                     plot.tag = element_text(face = "bold")) 

#plot_composite <- plot_grid(plot_prev, gee_plot_pr, glm_plot_pd, nrow=1, ncol=3)

#plot_composite <- grid.arrange(plot_prev, gee_plot_pr, glm_plot_pd, ncol=3, 
                              # nrow=1, widths=c(4, 2, 2))

#plot_composite

#plot_composite <- plot_grid(gee_plot_pr, glm_plot_pd, nrow=1, ncol=2)

plot_prev_composite <- plot_grid(plot_prev, glm_plot_pr, glm_plot_pd, ncol=1, 
                               nrow=3#, bottom = quote("Monsoon season")
                               )
plot_prev_composite
```

```{r save}

ggsave(plot_prev_composite, file = here::here("2-initial-analysis", "output",
                      "plot_effectmodmonsoon_glm.pdf"),  height=110, width=88, units = "mm")

#ggsave(plot_prev_composite, file = here::here("2-initial-analysis", "output",
                     #"plot_effectmodmonsoon_glm.png"), height=5,width=2)

```


```{r session info}

sessionInfo()
```
